# Generated by Django 2.2 on 2020-02-06 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('lCustomer_id', models.AutoField(primary_key=True, serialize=False)),
                ('cSearchName', models.TextField()),
                ('cName', models.CharField(max_length=100)),
                ('vEmailSender', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'CUSTOMER',
            },
        ),
        migrations.CreateModel(
            name='CustomerDiscount',
            fields=[
                ('intCustomerDiscountId', models.AutoField(primary_key=True, serialize=False)),
                ('chvDescription', models.CharField(max_length=100)),
                ('dtmInsertDate', models.DateTimeField()),
                ('intCustomer', models.ForeignKey(db_column='intCustomerId', on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'db_table': 'CUSTOMER_DISCOUNT',
            },
        ),
    ]
