# Generated by Django 2.2 on 2020-04-06 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_name', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('email_sender', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReplicaCustomer',
            fields=[
                ('lCustomer_id', models.AutoField(primary_key=True, serialize=False)),
                ('cSearchName', models.TextField()),
                ('cName', models.CharField(max_length=100)),
                ('vEmailSender', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'CUSTOMER',
            },
        ),
        migrations.CreateModel(
            name='ReplicaCustomerDiscount',
            fields=[
                ('intCustomerDiscountId', models.AutoField(primary_key=True, serialize=False)),
                ('intCustomerId', models.IntegerField()),
                ('chvDescription', models.CharField(max_length=100)),
                ('dtmInsertDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'CUSTOMER_DISCOUNT',
            },
        ),
        migrations.CreateModel(
            name='CustomerDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('insert_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
    ]
